[package]
name = "tickey_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.28.2"

kira = "0.10.3"
anyhow = "1.0.79"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
rand = "0.9.0"
once_cell = "1.20.3"
tokio = { version = "*", features = ["full"] }
